scheme: group_labels_inner_dirichlet
params:
  dataset: ${task.dataset}
  num_partitions: ${trainer.num_clients}
  group_names: [fast, slow]
  group_fractions: [0.8, 0.2]
  group_label_lists: [[0,1,2,3,4,5],[4,5,6,7,8,9]]
  force_sort_groups: true
  partition_by: ${task.label_column}
  alpha: 0.5
  max_attempts: 500 
  min_num_samples: 5
  seed: 0
  save_dir: ${environments_dir}